### PR TITLE
BZ #1290684 - Replace regex to accommodate change in crm_mode output

### PR DESCRIPTION
**Pull request by gouthampacha**
Remove the regex used and just grab the second column of the output
from the crm_mode command to get members.

### CODE REVIEW

**Comment by jguiditta** [comment]
Any chance I can get you to rebase this against master, and then I will cherry-pick it back to juno?  this same issue will be present there, so I would prefer to follow the normal course of 'fix master, then backport', if possible.

**Comment by jguiditta** [comment]
I think the PR itself also needs to be updated to point at master, this is why there are an extra 194 commits now,,,

**Comment by gouthampacha** [comment]
I created a new pull request, couldn't figure out if I could update this one to master. 

https://github.com/redhat-openstack/astapor/pull/570

**Comment by jguiditta** [comment]
Ok, merged the other one, and cherry-picked the commit back to this branch, closing

**Pull request closed without merging**
