### PR TITLE
BZ #1193448 - Introduce vncproxy_host parameter

### PR DESCRIPTION
**Pull request by fghaas**
https://bugzilla.redhat.com/show_bug.cgi?id=1193448

### CODE REVIEW

**Comment by jguiditta** [comment]
As mentioned in the BZ, I thin your idea to use pick and gracefully fall back to using nova_host would be a less invasive approach and allow us to pull this in more quickly due to less impact on dependent projects like staypuft

**Comment by jguiditta** [comment]
Two minor requests.  I was just trying to apply this patch to a setup I have, and noticed that it is pretty far behind master.  Still mergable here, but not easily via git am <patch> (I would have to rewind, apply, then rebase to get back to current).  Could you rebase this patch?
Second, and ths one is super minor, for readability, I try to have any new additions keep params in class signatures in alphabetical order.  Could you change that order as well?  I am not sure of your availability or timezone, so if this is not possible I can do both myself in a bit and just amend your patch, pushing that version.  If I don't hear back from you in the next hour or 2, I'll assume you are not free and make those changes.  Thanks again for the contribution (I'll test this by manually making the same changes for now on my setup)

**Comment by jguiditta** [comment]
Functional ack, seems to work just fine in both variants

**Comment by fghaas** [comment]
@jguiditta Rebased and fixed up as per your request. Let me know if that looks better.

**Comment by jguiditta** [comment]
Perfect, thanks!

**Pull request merged**
