### PR TITLE
BZ #1195476 - Provisioning of NetApp Cinder fails

### PR DESCRIPTION
**Pull request by rhefner1**
This change fixes a few things:
  1. When calling cinder::backend:netapp, use the right params
  2. Add params to ::storage_backend::cinder
  3. Changes to ::cinder::multi_instance_type to support resource
     prefix other than eqlx. That should be in $resource_prefix
     instead of being hard-coded.  Any issues with that?
  4. A few style changes

### CODE REVIEW

**Comment by jguiditta** [comment]
+1, these all look like reasonable/good changes and fixes.

**Comment by jguiditta** [comment]
@rhefner1 - would you mind just amending the commit message for this to match our BZ standard messages?  That format is:
```
BZ #12345 - Short summary

https://bugzilla.redhat.com/show_bug.cgi?id=12345

Longer summary if needed.
```

Once you have done that, I am happy to merge this.  Thanks

**Comment by rhefner1** [comment]
@jguiditta - does that look correct?

**Comment by jguiditta** [comment]
@rhefner1 perfect, thank you!

**Pull request merged**
