### PR TITLE
BZ #1199625 - additional ceph.conf settings

### PR DESCRIPTION
**Pull request by cwolferh**
https://bugzilla.redhat.com/show_bug.cgi?id=1199625

Adds two optional osd parameters.  Adds the ability to include the
[osd] and/or an [client.radosgw.gateway] sections in ceph.conf.  Adds
the ability to manage the rgw keyring file (similar to volumes and
images keyrings).  Adds a "manage_ceph_conf" boolean parameter so that
/etc/ceph/ceph.conf may or may not be written by puppet.  Adds an
extra_conf_lines array parameter so that arbirtrary additions may be
made to ceph.conf.  Renames compute param from
ceph_osd_pool_default_size to ceph_osd_pool_size for consistency.

### CODE REVIEW

**Comment by cwolferh** [comment]
Tested e2e and was able to launch a vm with:

    ceph_cluster_network: 192.168.201.0/24
    ceph_conf_include_osd_global: true
    ceph_conf_include_rgw: false
    ceph_extra_conf_lines: []
    ceph_fsid: 904c8491-5c16-4dae-9cc3-6ce633a7f4cc
    ceph_images_key: AQAfHBdUKLnUFxAAtO7WPKQZ8QfEoGqH0CLd7A==
    ceph_mon_host:
    - 192.168.200.10
    - 192.168.200.20
    - 192.168.200.30
    ceph_mon_initial_members:
    - c1a1
    - c1a2
    - c1a3
    ceph_osd_journal_size: '1000'
    ceph_osd_mkfs_options_xfs: -f -i size=2048 -n size=64k
    ceph_osd_mount_options_xfs: -o inode64,noatime,logbsize=256k
    ceph_osd_pool_size: '1'
    ceph_public_network: 192.168.200.0/24
    ceph_rgw_config_suffix: radosgw.gateway
    ceph_rgw_hostname: ''
    ceph_rgw_key: ''
    ceph_rgw_keyring_filename: /etc/ceph/ceph.client.radosgw.keyring
    ceph_volumes_key: AQAfHBdUsFPTHhAAfqVqPq31FFCvyyO7oaOQXw==

More permutations around boolean vars above should be tested, however.

**Comment by Steve-Hand** [comment]
I’d really like to be able to specify one stanza, one configuration for all RGW instances. I think this works as long as there is one RGW instance per server. Is that possible?

I really do not see value is customizing the RGW instance configuration. But I do see value in having a single, uniform configuration of all RGW instances.

What about using Ceph dynamic variable as a means to have a single RGW configuration? Could we set the host parameter to the Ceph dynamic '$host' variable. We could even use other Ceph dynamic variable to run more than one RGW instance on a given server, but that's not something we need.

**Comment by cwolferh** [comment]
Tested a number of things in this PR, including:
*TEST manage_ceph_conf
*TEST SETTING ceph_rgw_key TO NON EMPTY CREATES the rgw keyring file
*TEST CHANGING ceph_conf_include_rgw FROM false TO true CAUSES STANZA TO BE ADDED TO ceph.conf
*TEST CHANGING ceph_conf_include_osd_global FROM true TO false CAUSES [osd] STANZA TO BE REMOVED TO ceph.conf
*TEST SETTING OTHER OSD PARAMS
*TEST SETTING ceph_extra_conf_lines TO NON-EMPTY ARRAY APPENDS TO ceph.conf
*TEST CHANGING ceph_rgw_hostname

The gory details of which can be found here:
https://gist.github.com/cwolferh/b2b7c5320ab451731f27

**Comment by cwolferh** [comment]
I have just updated this PR so that the radosgw stanza's look like:

    [client.radosgw.c1a5]
    host = c1a5
    keyring = /etc/ceph/ceph.client.radosgw.keyring
    rgw socket path = /var/run/ceph/ceph.radosgw.c1a5.fastcgi.sock
    log file = /var/log/radosgw/client.radosgw.c1a5.log
    rgw print continue = false

where c1a5 is derived from "hostname -s".  Note that this still may be overridden with parameter $ceph_rgw_hostname.

**Comment by cwolferh** [comment]
Updated again.  The $ceph_rgw_hostname parameter been replaced with an array param $ceph_rgw_hostnames.  Given yaml of:

    ceph_rgw_hostnames:
    - rgwhost1
    - rgwhost2

The following stanzas appear in ceph.conf:

    [client.radosgw.rgwhost1]
    host = rgwhost1
    keyring = /etc/ceph/ceph.client.radosgw.keyring
    rgw socket path = /var/run/ceph/ceph.radosgw.rgwhost1.fastcgi.sock
    log file = /var/log/radosgw/client.radosgw.rgwhost1.log
    rgw print continue = false

    [client.radosgw.rgwhost2]
    host = rgwhost2
    keyring = /etc/ceph/ceph.client.radosgw.keyring
    rgw socket path = /var/run/ceph/ceph.radosgw.rgwhost2.fastcgi.sock
    log file = /var/log/radosgw/client.radosgw.rgwhost2.log
    rgw print continue = false

**Pull request merged**
