### PR TITLE
BZ #1182219 - Add role heat_stack_owner for admin user.

### PR DESCRIPTION
**Pull request by jguiditta**
https://bugzilla.redhat.com/show_bug.cgi?id=1182219

Previously, the role was created, but not assigned to the admin user.

### CODE REVIEW

**Comment by jguiditta** [comment]
After running with this, I have:
```
 keystone --os-username admin --os-password weakpw --os-tenant-name admin user-role-list
+----------------------------------+------------------+----------------------------------+----------------------------------+
|                id                |       name       |             user_id              |            tenant_id             |
+----------------------------------+------------------+----------------------------------+----------------------------------+
| 771cf97c3ae34e4ba88ff56116281c70 |      admin       | 9b456d996ed74d398b222cea11b4d308 | a4ae24eff83d4ec887f7670449c23583 |
| 727004efb5994b18a38c1838e1a4f9a9 | heat_stack_owner | 9b456d996ed74d398b222cea11b4d308 | a4ae24eff83d4ec887f7670449c23583 |
+----------------------------------+------------------+----------------------------------+----------------------------------+
```

**Comment by cwolferh** [comment]
I got the error:

    d1a2 15:27:25 Debug: /Stage[main]/Quickstack::Pacemaker::Heat/Quickstack::Keystone::Role[heat_stack_owner]/Exec[add role heat_stack_owner]/returns: Exec try 1/10
    d1a2 15:27:25 Error: Could not find command '/usr/bin/keystone
    d1a2 15:27:25 '

I confirmed python-keystoneclient which owns /usr/bin/keystone was installed before puppet attempted the above.  It looks oddly like a whitespace issue.

**Comment by jguiditta** [comment]
On 22/01/15 15:58 -0800, cwolferh wrote:
>   I got the error:
>d1a2 15:27:25 Debug: /Stage[main]/Quickstack::Pacemaker::Heat/Quickstack::Keysto
>ne::Role[heat_stack_owner]/Exec[add role heat_stack_owner]/returns: Exec try 1/1
>0
>d1a2 15:27:25 Error: Could not find command '/usr/bin/keystone
>d1a2 15:27:25 '
>
>   I confirmed python-keystoneclient which owns /usr/bin/keystone was
>   installed before puppet attempted the above. It looks oddly like a
>   whitespace issue.
>
Blearg, sorry, I forgot that I had fixed this in my test, but didn't
update the PR, which I just did.  For the code readability line-breaks
I have, each line needs to end with '\', otherwise puppet doesn't
execute it properly.  I had omitted those on the first rev.

**Comment by jguiditta** [comment]
Hmph, and after I 'fixed' it above, a fresh run results in:
  Expecting an auth URL via either --os-auth-url or env[OS_AUTH_URL]

I am not sure how this worked for me before, I don't recall ever setting that.  I have another approach I am going to try now, so please hold on testing until I update comments here again

**Comment by jguiditta** [comment]
I need to blow away my clients and retry this fresh now, but with this version I get:
```
[[root@c1a2 ~(openstack_admin)]# keystone --os-username admin --os-password weakpw --os-tenant-name admin user-role-list
+----------------------------------+------------------+----------------------------------+----------------------------------+
|                id                |       name       |             user_id              |            tenant_id             |
+----------------------------------+------------------+----------------------------------+----------------------------------+
| 9fe2ff9ee4384b1894a90878d3e92bab |     _member_     | 7ccdd531a6df4796b56c34ece09de086 | 6fcdf917436345f8923f2c8ff131dc40 |
| 604ad149a74c46a5948b017a0fb683f4 |      admin       | 7ccdd531a6df4796b56c34ece09de086 | 6fcdf917436345f8923f2c8ff131dc40 |
| 04613af5c1e440f78354f067383c3b32 | heat_stack_owner | 7ccdd531a6df4796b56c34ece09de086 | 6fcdf917436345f8923f2c8ff131dc40 |
+----------------------------------+------------------+----------------------------------+----------------------------------+
```

Note that the one downside is it does require a second puppet run, but as the exec can be avoided this way and we can rely on keystone module to do what we want, I think it is worth the one extra run.  Services will all be configured in the first run still, but roles is added afterward for stack_owner to the admin user. Note that Staypuft does multiple runs in all cases anyway

**Comment by jguiditta** [comment]
Updated, so after the second run, we have:
```
 keystone --os-username admin --os-password weakpw --os-tenant-name admin user-role-list
+----------------------------------+------------------+----------------------------------+----------------------------------+
|                id                |       name       |             user_id              |            tenant_id             |
+----------------------------------+------------------+----------------------------------+----------------------------------+
| 6c45b0fd80d74cc5951348d10a2686f4 |      admin       | 9f293678c74340c98e3edb044c531f49 | b6523a41b08b4547808dba04601c50bb |
| 41dc6c1e054543cab2c39f15d90a6400 | heat_stack_owner | 9f293678c74340c98e3edb044c531f49 | b6523a41b08b4547808dba04601c50bb |
+----------------------------------+------------------+----------------------------------+----------------------------------+
```

**Comment by cwolferh** [comment]
Confirmed.  With a fresh install after a second puppet run I get:

    # keystone --os-username admin --os-password weakpw --os-tenant-name admin user-role-list
    +----------------------------------+------------------+----------------------------------+----------------------------------+
    |                id                |       name       |             user_id              |            tenant_id             |
    +----------------------------------+------------------+----------------------------------+----------------------------------+
    | c9a35e9e7bd34a52a34c5edb30866277 |      admin       | b7e80bb1a98e40f983674b994ca9fd33 | d33b33fa306a42d68bdf1c432d4eeaed |
    | c8ab31247b0f43fc87e530d0f74423e1 | heat_stack_owner | b7e80bb1a98e40f983674b994ca9fd33 | d33b33fa306a42d68bdf1c432d4eeaed |
    +----------------------------------+------------------+----------------------------------+----------------------------------+

**Pull request merged**
