### PR TITLE
Fix ceilometer+redis to use vip and have central be a/a.

### PR DESCRIPTION
**Pull request by jguiditta**

### CODE REVIEW

**Comment by jguiditta** [comment]
Here is what my haproxy config for redis looks like after this patch:
```
listen redis
  bind 192.168.201.14:6379
  mode tcp
  option tcplog
  tcp-check send PINGrn
  tcp-check expect string +PONG
  tcp-check send info replicationrn
  tcp-check expect string role:master
  tcp-check send QUITrn
  tcp-check expect string +OK
  server pcmk-c1a1 192.168.200.10:6379 check inter 1s
  server pcmk-c1a2 192.168.200.20:6379 check inter 1s
  server pcmk-c1a3 192.168.200.30:6379 check inter 1s
```

**Comment by jguiditta** [comment]
Also, added check to make sure vip is not blank, which will fail compilation instead of failing install.  You will get a message like:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template haproxy/haproxy_listen_block.erb:
  Filepath: /usr/share/ruby/vendor_ruby/puppet/parser/functions/template.rb
  Line: 19
  Detail: Failed to parse template haproxy/fragments/_bind.erb:
  Filepath: /usr/share/ruby/vendor_ruby/puppet/parser/functions/fail.rb
  Line: 3
  Detail: Invalid IP address or hostname []
```

**Comment by jguiditta** [comment]
Updated, working haproxy block that works looks like this (thanks crag!):
```
listen redis
  bind 192.168.201.14:6379
  mode tcp
  option tcplog
  option tcp-check
  tcp-check send PING\r\n
  tcp-check expect string +PONG
  tcp-check send info\ replication\r\n
  tcp-check expect string role:master
  tcp-check send QUIT\r\n
  tcp-check expect string +OK
  server pcmk-c1a1 192.168.200.10:6379 check inter 1s
  server pcmk-c1a2 192.168.200.20:6379 check inter 1s
  server pcmk-c1a3 192.168.200.30:6379 check inter 1s
```

**Comment by cwolferh** [comment]
Works for me.

**Pull request merged**
