### PR TITLE
BZ #1240362 - Update to compute node's cinder/catalog_info.

### PR DESCRIPTION
**Pull request by cwolferh**
https://bugzilla.redhat.com/show_bug.cgi?id=1240362

Updated parameter in nova.conf now looks like:
[cinder]
catalog_info=volumev2:cinderv2:internalURL

### CODE REVIEW

**Comment by cwolferh** [comment]
After patch, nova.conf on compute nodes (neutron or nova network) includes:

    [cinder]
    ...
    catalog_info=volumev2:cinderv2:internalURL

Note that a fresh foreman install may be needed to update default hostgroup params.

Verify by setting debug=True manually in nova.conf, restarting openstack-nova-compute, and checking requests to the cinder API in /var/log/nova/nova-compute.log, e.g.:

     2015-07-07 17:48:00.388 25824 DEBUG keystoneclient.session [req-accbd6ba-e697-4359-ae9a-2fcb86805620 c5562f3c8b0441088a682200c14eecd1 d0739fde273b4818a27599b20a3c3b3d - - -] REQ: curl -g -i -X POST http://192.168.201.84:8776/v2/d0739fde273b4818a27599b20a3c3b3d/volumes/e7420585-52fd-44b5-933b-05c68b5b51f4/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}ac32cb4cea3ed76cc34632c40406c6d50e3937dc" -d '{"os-attach": {"instance_uuid": "4e6ea18d-03bb-44e3-817e-f76612185ae6", "mountpoint": "/dev/vdc", "mode": "rw"}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneclient/session.py:195

**Comment by arkadykanevsky** [comment]
both volume and cinder need to specify version #? 
Is there a place where we can globally specify which API version to use for all cinder commands?
Let it be inherited for all parameters.

**Comment by cwolferh** [comment]
@arkadykanevsky , that is just being consistent with the name and type fields in "keystone service-list."  E.g:

    +----------------------------------+-------------------+----------------+----------------------------------+
    |                id                |        name       |      type      |           description            |
    +----------------------------------+-------------------+----------------+----------------------------------+
    | 7d8e677cb58e470fa6bbcc41a09639fa |     ceilometer    |    metering    |    Openstack Metering Service    |
    | 2854c1c3d19d412ba8d190519309695d |       cinder      |     volume     |          Cinder Service          |
    | 1629087081a84b84a0358b0f95c955b1 |      cinderv2     |    volumev2    |        Cinder Service v2         |
    | aef9014ab4d34df0ac4562608e061414 |       glance      |     image      |     OpenStack Image Service      |
    | 34410c6b6d814c92bb9609230ff74479 |        heat       | orchestration  | Openstack Orchestration Service  |
    | b2e1889f7bf149b8b92e068fc5b86202 |      heat-cfn     | cloudformation | Openstack Cloudformation Service |
    | 7999167c8510424dab00a084251d0410 | identity_endpoint |    identity    |    identity_endpoint service     |
    | 9361002087f741249b087d7505a93195 |      neutron      |    network     |    Neutron Networking Service    |
    | ff7f72e9d75549a281fbfb93060d2670 |        nova       |    compute     |    Openstack Compute Service     |
    | 1a9426b4feb64514a33a0d5a12435d71 |      nova_ec2     |      ec2       |           EC2 Service            |
    | 48148156f4004e748afd7272c8a0ab4a |       novav3      |   computev3    |   Openstack Compute Service v3   |
    +----------------------------------+-------------------+----------------+----------------------------------+

**Comment by jguiditta** [comment]
Tested with debug set to on, and in nova-compute,log, I see:
```
2015-07-08 11:22:49.571 6762 DEBUG keystoneclient.session [req-6819900e-0f23-44a0-b1e4-cbefb8ed44ff 10b0a54627bb401b99a0a850e0399a52 42ddc88b96724175bf80432b5ab7ee31 - - -] REQ: curl -g -i -X POST http://192.168.201.84:8776/v1/42ddc88b96724175bf80432b5ab7ee31/volumes/acb4689c-26e9-447b-aabd-7ffab35ba08f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}71e598893c972c8feb10bfd8707cd71d44ab3949" -d '{"os-attach": {"instance_uuid": "56395461-d2f1-4ee4-b906-75d93a06e1b1", "mountpoint": "/dev/vdb", "mode": "rw"}}' _http_log_request /usr/lib/python2.7/site-packages/keystoneclient/session.py:195
```
Which maps to:
```
pcs status | grep 84
 ip-cinder-prv-192.168.201.84   (ocf::heartbeat:IPaddr2):       Started pcmk-c1a2
```

So, internal/private url seems to be getting used here.

**Pull request merged**
